name: Build and deploy React app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ソースコードをチェックアウト
      - uses: actions/checkout@v4

      # Node.jsのセットアップ
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # npmインストールとビルド
      - name: Install dependencies and build the app
        run: |
          npm install
          npm run build

      # ビルド成果物をZIP形式でアップロード
      - name: Zip build artifacts
        run: zip -r build.zip build/

      # アーティファクトをアップロード（デプロイ用）
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # ビルド成果物をダウンロード
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app

      # ZIPファイルを解凍
      - name: Unzip build artifacts
        run: unzip build.zip -d ./build

      # Azure Web Appにデプロイ
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'your-app-name'
          slot-name: 'Production'
          package: ./build
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
